import "./globals.css"
import { Inter } from "next/font/google"
import ReactQueryProviders from "@/utils/react-query/query-providers"
import { Providers as ChakraProviders } from "@/theme/theme_providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProviders>
          <ChakraProviders>{children}</ChakraProviders>
        </ReactQueryProviders>
      </body>
    </html>
  )
}
